POST http://localhost:3001/
Content-Type: application/json

{
    "name": "Cotton Socks",
    "quantity": 73,
    "price": 7.99,
    "color": "white",
    "size": "M"
}

###
POST http://localhost:3001/
Content-Type: application/json

{
  "name": "Coat",
  "quantity": 25,
  "price": 89.99,
  "color": "blue",
  "size": "M"
}

###
POST http://localhost:3001/
Content-Type: application/json

{
  "name": "Hoodie",
  "quantity": 3,
  "price": 60.0,
  "color": "orange",
  "size": "L"
}

###
POST http://localhost:3001/
Content-Type: application/json

{
  "name": "Stickers",
  "quantity": 200,
  "price": 2.99,
  "color": "white",
  "size": "S"
}

###
POST http://localhost:3001/
Content-Type: application/json

{
  "name": "Crop Top",
  "quantity": 10,
  "price": 15.00,
  "color": "white",
  "size": "L"
}

###
POST http://localhost:3001/
Content-Type: application/json

{
  "name": "T-Shirt",
  "quantity": 44,
  "price": 29.99,
  "color": "black",
  "size": "M"
}

